initiate many-to-many relationship for users and stocks
LeeRenJie/Learn-Ruby pull request #125
Opened 2021-08-08 13:19 UTC by LeeRenJie

depends on #124

2021-08-10 09:06 UTC, tlkiong requested changes

2021-08-10 09:06 UTC, tlkiong commented on finance-tracker/config/routes.rb
> +  resources :user_stocks
why at the top of router file?

2021-08-11 15:26 UTC, tlkiong requested changes
Why do you need to have `UserStock` model?
*if you want to tell me its required, you can try removing the model file (keep the migration). Then change the has_many user_stocks & has_many xx through user_stocks with:

```
has_and_belongs_to_many xx
```

2021-08-11 15:29 UTC, LeeRenJie commented
> Why do you need to have UserStock model?

initiate many-to-many relationships between users and stocks through this table. A user can track many stocks, a stock can be tracked by many different users

2021-08-12 09:30 UTC, LeeRenJie commented
> Why do you need to have `UserStock` model?
> *if you want to tell me its required, you can try removing the model file (keep the migration). Then change the has_many user_stocks & has_many xx through user_stocks with:
> 
> ```
> has_and_belongs_to_many xx
> ```

We need UserStock model to initiate the many-to-many association through this table with `has_many xx through`. Because it is better compared to `has_and_belongs_to_many` since we can add more columns to the join table in the future.

2021-08-12 15:58 UTC, tlkiong approved these changes
Very good.
Never ever initiate a many to many relationship without the join model.

2021-08-12 15:58 UTC, merged