Sign up form for user to enter their username email and password
LeeRenJie/Learn-Ruby pull request #20
Opened 2021-05-15 11:14 UTC by LeeRenJie

depends on #19

2021-05-16 11:12 UTC, tlkiong requested changes

2021-05-16 11:12 UTC, tlkiong commented on alpha-blog/app/views/users/_form.html.erb
> +            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Enter a new password" %>
No need `confirm password`?

2021-05-17 12:22 UTC, LeeRenJie commented on alpha-blog/app/views/users/_form.html.erb
> +            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Enter a new password" %>
havent😂

2021-05-19 12:43 UTC, tlkiong approved these changes

2021-05-19 12:44 UTC, merged