feat(users): add user with scaffold and has a self join model
LeeRenJie/Learn-Ruby pull request #66
Opened 2021-07-06 15:00 UTC by LeeRenJie

`User.rb` model
```ruby
class User < ApplicationRecord
  belongs_to :mother, class_name: "User", optional: true
  belongs_to :father, class_name: "User", optional: true
  has_one :grandfather, through: :father, source: :father
  has_one :grandmother, through: :father, source: :mother
end
```

1. `belongs_to :mother, class_name: "User", optional: true` and `belongs_to :father, class_name: "User", optional: true`
    1. `belongs_to` will create a foreign_key in the User model called as `mother_id` and `father_id1 respectively
    1. The purpose of `:class_name` is to allow me to use a class that is different from the one Rails expects. When I have a `belongs_to :mother` or `belongs_to :father` in the model, Rails would expect that to point to a parent class called `Mother` or `Father`. But my code tells Rails to skip looking for a `Mother`  or `Father` class and instead look to the User model.
    1. `optional: true` allows the `mother_id` and `father_id` column to be `nil`

1.  `  has_one :grandfather, through: :father, source: :father` and `has_one :grandmother, through: :father, source: :mother`
    1. The `has_one :through` association  helps set up a one-to-one association with a third model (grandfather/grandmother) by going through a second model (father).
    1. `:source` option specifies the source association name for the `has_one :through` association. I am renaming the father and mother association to father. If I don't provide the `:source`, Rails will look for an association called grandfather/grandmother in the Father(User) class. I have to tell it to use the father/mother association in the Father(User) class in order to get the right object.

My final table created with the data:
![image](https://user-images.githubusercontent.com/67599130/124756828-7dc6cd80-df5f-11eb-889d-c740a46d48aa.png)

2021-07-07 13:13 UTC, tlkiong commented on test-app/db/schema.rb
> +    t.integer "mother_id"
Change this to use `t.references`
Go google how to change this in your migration file itself

2021-07-07 13:14 UTC, tlkiong requested changes
Can you paste the output in your terminal of the following:

```
user 
user.mother
user.father
user.grandmother
user.grandfather
```

2021-07-07 14:59 UTC, LeeRenJie commented
> Can you paste the output in your terminal of the following:
> 
> ```
> user 
> user.mother
> user.father
> user.grandmother
> user.grandfather
> ```

```ruby
irb(main):001:0> user = User.find(1)
   (0.3ms)  SELECT sqlite_version(*)
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
=> #<User id: 1, name: "rj", mother_id: 3, father_id: 2>

irb(main):002:0> user
=> #<User id: 1, name: "rj", mother_id: 3, father_id: 2>

irb(main):003:0> user.mother
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 3], ["LIMIT", 1]]
=> #<User id: 3, name: "mother", mother_id: nil, father_id: nil>

irb(main):004:0> user.father
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
=> #<User id: 2, name: "father", mother_id: 4, father_id: 5>

irb(main):005:0> user.grandmother
  User Load (0.1ms)  SELECT "users".* FROM "users" INNER JOIN "users" "fathers_grandmother" ON "users"."id" = "fathers_grandmother"."mother_id" WHERE "fathers_grandmother"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
=> #<User id: 4, name: "grandmother", mother_id: nil, father_id: nil>

irb(main):006:0> user.grandfather
  User Load (0.1ms)  SELECT "users".* FROM "users" INNER JOIN "users" "fathers_grandfather" ON "users"."id" = "fathers_grandfather"."father_id" WHERE "fathers_grandfather"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
=> #<User id: 5, name: "grandfather", mother_id: nil, father_id: nil>
```

2021-07-08 13:16 UTC, tlkiong approved these changes

2021-07-08 13:17 UTC, merged