link to pages from nav menu
LeeRenJie/Learn-Ruby pull request #81
Opened 2021-07-20 12:37 UTC by LeeRenJie

depends on #80

2021-07-20 14:26 UTC, tlkiong requested changes

2021-07-20 14:26 UTC, tlkiong commented on message-me/app/views/layouts/_navigation.html.erb
> +      <%= link_to 'Log out', login_path, class: "item" %>
better to not use any link to if it don't exist yet so that you don't forget

2021-07-21 10:14 UTC, tlkiong requested changes
please double triple check ya

2021-07-21 10:14 UTC, tlkiong commented on message-me/app/views/sessions/new.html.erb
> +  Log in to continue
???

2021-07-21 10:14 UTC, tlkiong commented on message-me/app/views/sessions/new.html.erb
> +      <div class="ui form">
form tag?

2021-07-21 10:19 UTC, LeeRenJie commented on message-me/app/views/sessions/new.html.erb
> +  Log in to continue
forgot merge 😅

2021-07-21 13:39 UTC, tlkiong approved these changes

2021-07-21 13:39 UTC, merged